### ISSUE TITLE
7d Case Avg per 100k Issue 

### ISSUE THREAD

**Issue by kliu0** [geomatics21aspc/Cases_timeseries#1]
Hi, we noticed that the cases_last_7_days_per100k for Saskatchewan (Far North East) has been 0 from October 15. This health region has been a hotspot area and we were wondering if a line of code may have been deleted?

![image](https://user-images.githubusercontent.com/92118309/140969675-ba60e493-2cb2-4ea9-a322-eba1d32af155.png)

Thank you,
Karen

**Comment by kevsieb** [comment]
Hi Karen, thanks for pointing this. There was indeed an issue; the regions cases were mixed up and Far North East was actually displaying Fr North Central cases. The problem was fixed on Wednesday November 10.

**Comment by kliu0** [comment]
Hi, thank you for letting me know. Would you be able to confirm how many weeks this problem was ongoing for! 

Karen

**Comment by kevsieb** [comment]
The change that caused the error was implemented the day before you have opened this topic, on Monday, November 8.
The timeseries, are recalculated every day so this does not affect the data anymore.
Also, I have edited my last message, the data were actually wrongly referring to Far North Central, not Yukon.
